spring.datasource.url=jdbc:mysql://localhost:3306/sneak
spring.datasource.username=root
spring.datasource.password=cotoda10

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=T9t9b2F1Lksndf983nDlmf9JQlznbmRZkLmASR3kLxE=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

mercadopago.access.token=TEST-6704653566813108-061110-32034d8cb812784e62562d28af1af5d7-1009321633